app.banco=SQL Server Standard 2025

sqlserver.db.url=jdbc:sqlserver://localhost:14330;databaseName=CadastroClientes;integratedSecurity=true;authenticationScheme=NativeAuthentication;encrypt=true;trustServerCertificate=true

sqlserver.db.usuario=
sqlserver.db.senha=
